version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PLATFORM=linux/amd64
        platform: linux/amd64
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:5.7
        platform: linux/amd64
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "8081:80"

volumes:
    dbdata:
